services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://model-runner.docker.internal/engines/llama.cpp/v1
      - OPENAI_API_KEY=na
      - WEBUI_NAME=Docker Model Runner Interface
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llm-runner
      - embeddings-runner-gemma
      - embeddings-runner-mxbai
      - embeddings-runner-granite
  llm-runner:
    provider:
      type: model
      options:
        model: ai/smollm3:Q8_0

  embeddings-runner-gemma:
    provider:
      type: model
      options:
        model: ai/embeddinggemma

  embeddings-runner-mxbai:
    provider:
      type: model
      options:
        model: ai/mxbai-embed-large:335M-F16

  embeddings-runner-granite:
    provider:
      type: model
      options:
        model: ai/granite-embedding-multilingual

volumes:
  open-webui: